#!/usr/bin/env npx tsx
/**
 * Build-time generator for repo-owned edge artifacts: public/robots.txt and
 * public/.well-known/security.txt. Runs at prebuild (after csp.ts). robots.txt
 * is stable and committed; security.txt carries a per-build Expires and is
 * gitignored (generated only when SECURITY_CONTACT is set). See
 * docs/superpowers/specs/2026-06-27-security-story-hardening-design.md §C1.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { readConfig } from "./config";

// Maintained from https://darkvisitors.com/agents — check periodically for new entries.
export const aiCrawlers = [
  "GPTBot",
  "ChatGPT-User",
  "Google-Extended",
  "anthropic-ai",
  "ClaudeBot",
  "Claude-Web",
  "CCBot",
  "PerplexityBot",
  "Bytespider",
  "Amazonbot",
  "FacebookBot",
  "Applebot-Extended",
  "cohere-ai",
  "Diffbot",
  "ImagesiftBot",
  "Omgilibot",
  "YouBot",
];

/**
 * robots.txt body. Allows all crawlers by default. When `blockAI` is true,
 * appends Disallow directives for known AI training crawlers (#408, C4).
 */
export function buildRobotsTxt(blockAI = false): string {
  let body = `# robots.txt — generated by scripts/edge-artifacts.ts
User-agent: *
Disallow:
`;
  if (blockAI) {
    body += `\n# AI crawler / training bot directives (BLOCK_AI=true in .site-config)\n`;
    for (const bot of aiCrawlers) {
      body += `\nUser-agent: ${bot}\nDisallow: /\n`;
    }
  }
  return body;
}

/**
 * RFC 9116 security.txt body, or null when no usable contact is configured — a
 * blank value, or one that is neither a recognized URI (http/https/mailto/tel)
 * nor a bare email. We skip the file rather than emit an invalid Contact field
 * (RFC 9116 §2.5 requires a URI). `Expires` is one year from `now` at UTC
 * midnight, regenerated every build so it never lapses.
 */
export function buildSecurityTxt(contact: string | undefined, siteUrl: string, now: Date): string | null {
  const trimmed = (contact ?? "").trim();
  if (trimmed.length === 0) return null;
  let contactUri: string;
  if (/^(https?:|mailto:|tel:)/i.test(trimmed)) {
    contactUri = trimmed;
  } else if (trimmed.includes("@")) {
    contactUri = `mailto:${trimmed}`;
  } else {
    return null; // not a URI and not an email — skip rather than emit invalid RFC 9116
  }
  const expires = new Date(
    Date.UTC(now.getUTCFullYear() + 1, now.getUTCMonth(), now.getUTCDate()),
  ).toISOString();
  const canonical = `${siteUrl.replace(/\/+$/, "")}/.well-known/security.txt`;
  return `Contact: ${contactUri}
Expires: ${expires}
Canonical: ${canonical}
`;
}

function main(): void {
  const publicDir = resolve(process.cwd(), "public");
  const blockAI = (readConfig("BLOCK_AI") ?? "").trim().toLowerCase() === "true";
  writeFileSync(resolve(publicDir, "robots.txt"), buildRobotsTxt(blockAI), "utf-8");
  console.log("Wrote public/robots.txt");

  const siteUrl = readConfig("SITE_URL") ?? "https://example.com";
  const securityTxt = buildSecurityTxt(readConfig("SECURITY_CONTACT"), siteUrl, new Date());
  if (securityTxt !== null) {
    const wellKnown = resolve(publicDir, ".well-known");
    mkdirSync(wellKnown, { recursive: true });
    writeFileSync(resolve(wellKnown, "security.txt"), securityTxt, "utf-8");
    console.log("Wrote public/.well-known/security.txt");
  } else {
    console.log("Skipped security.txt (no SECURITY_CONTACT in .site-config)");
  }
}

// Run only when invoked directly (e.g. `npx tsx scripts/edge-artifacts.ts`), never on import.
if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main();
}
