#!/usr/bin/env npx tsx
/**
 * Build-time generator for repo-owned edge artifacts: public/robots.txt and
 * public/.well-known/security.txt. Runs at prebuild (after csp.ts). robots.txt
 * is stable and committed; security.txt carries a per-build Expires and is
 * gitignored (generated only when SECURITY_CONTACT is set). See
 * docs/superpowers/specs/2026-06-27-security-story-hardening-design.md §C1.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { readConfig } from "./config";

/** robots.txt body. Allows all crawlers; AI-crawler directives are C4 (opt-in). */
export function buildRobotsTxt(): string {
  return `# robots.txt — generated by scripts/edge-artifacts.ts
User-agent: *
Disallow:
`;
}

function main(): void {
  const publicDir = resolve(process.cwd(), "public");
  writeFileSync(resolve(publicDir, "robots.txt"), buildRobotsTxt(), "utf-8");
  console.log("Wrote public/robots.txt");
}

// Run only when invoked directly (e.g. `npx tsx scripts/edge-artifacts.ts`), never on import.
if (process.argv[1] && resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  main();
}
