import Foundation

/// The site-settings representation of the RFC 8461 policy generated by the template.
///
/// This deliberately owns only the deterministic `.site-config` keys. The policy's HTTPS host
/// (`mta-sts.<domain>`) needs a valid certificate and a host mapping at the deploy provider, so
/// the UI names that prerequisite instead of pretending a TXT record alone enables MTA-STS.
public enum MTAStsPolicyAsset {
    public enum Mode: String, Sendable, CaseIterable, Identifiable, Equatable {
        case disabled
        case testing
        case enforce

        public var id: Self { self }
    }

    public struct Settings: Sendable, Equatable {
        public var mode: Mode
        /// Recipient/policy domain (without `_mta-sts.`); this is not necessarily the website host.
        public var domain: String
        /// One RFC 8461 MX pattern per line in the UI; persisted comma-separated for the template.
        public var mxHosts: String
        /// Optional RFC 8460 mailbox. A bare email is normalized to `mailto:` in the DNS record.
        public var reportMailbox: String

        public init(mode: Mode = .disabled, domain: String = "", mxHosts: String = "", reportMailbox: String = "") {
            self.mode = mode
            self.domain = domain
            self.mxHosts = mxHosts
            self.reportMailbox = reportMailbox
        }
    }

    public struct DNSRecord: Sendable, Equatable {
        public let name: String
        public let content: String

        public init(name: String, content: String) {
            self.name = name
            self.content = content
        }
    }

    public static func parseSettings(from config: String) -> Settings {
        let mode = Mode(rawValue: SiteConfigFile.value(forKey: "MTA_STS_MODE", in: config) ?? "") ?? .disabled
        let domain = SiteConfigFile.value(forKey: "MTA_STS_DOMAIN", in: config) ?? ""
        let hosts = SiteConfigFile.value(forKey: "MTA_STS_MX", in: config) ?? ""
        let reportMailbox = SiteConfigFile.value(forKey: "TLS_RPT_RUA", in: config) ?? ""
        return Settings(mode: mode, domain: normalizedDomain(domain), mxHosts: hosts.replacingOccurrences(of: ",", with: "\n"), reportMailbox: reportMailbox)
    }

    public static func install(_ settings: Settings, siteDirectory: URL) throws {
        let configURL = siteDirectory.appendingPathComponent(WebsiteAnalyticsAsset.configRelativePath)
        let config = (try? String(contentsOf: configURL, encoding: .utf8)) ?? ""
        let updated = SiteConfigFile.upsert([
            ("MTA_STS_MODE", settings.mode.rawValue),
            ("MTA_STS_DOMAIN", normalizedDomain(settings.domain)),
            ("MTA_STS_MX", normalizedMXList(settings.mxHosts).joined(separator: ",")),
            ("TLS_RPT_RUA", normalizedReportMailbox(settings.reportMailbox) ?? ""),
        ], into: config)
        guard updated != config else { return }
        try updated.write(to: configURL, atomically: true, encoding: .utf8)
    }

    /// DNS records to create in the policy domain. `id` is a stable alphanumeric fingerprint of
    /// the generated policy inputs, so it changes whenever its mode or allowed MX set changes.
    public static func dnsRecords(for domain: String, settings: Settings) -> [DNSRecord] {
        guard settings.mode != .disabled else { return [] }
        let mx = normalizedMXList(settings.mxHosts)
        guard !mx.isEmpty else { return [] }
        let policyID = policyID(mode: settings.mode, mxHosts: mx)
        var records = [DNSRecord(name: "_mta-sts.\(domain)", content: "v=STSv1; id=\(policyID);")]
        if let mailbox = normalizedReportMailbox(settings.reportMailbox) {
            records.append(DNSRecord(name: "_smtp._tls.\(domain)", content: "v=TLSRPTv1; rua=\(mailbox)"))
        }
        return records
    }

    public static func normalizedDomain(_ raw: String) -> String {
        normalizedMXList(raw).first(where: { !$0.hasPrefix("*.") }) ?? ""
    }

    /// RFC 8461 MX patterns: an ASCII domain name, optionally with only the complete first label
    /// replaced by `*`. This intentionally rejects IP literals and Unicode U-labels.
    public static func normalizedMXList(_ raw: String) -> [String] {
        let label = "[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?"
        let regex = try! NSRegularExpression(pattern: "^(?:\\*\\.)?(?:\(label)\\.)+\(label)$", options: [.caseInsensitive])
        var result: [String] = []
        for value in raw.split(whereSeparator: { $0 == "," || $0.isNewline }) {
            var host = value.trimmingCharacters(in: .whitespacesAndNewlines).lowercased()
            if host.hasSuffix(".") { host.removeLast() }
            let range = NSRange(host.startIndex..., in: host)
            if !host.isEmpty, regex.firstMatch(in: host, range: range) != nil, !result.contains(host) {
                result.append(host)
            }
        }
        return result
    }

    public static func normalizedReportMailbox(_ raw: String) -> String? {
        let value = raw.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !value.isEmpty else { return nil }
        if value.lowercased().hasPrefix("mailto:"), value.dropFirst(7).contains("@") { return value }
        if value.contains("@"), !value.contains(" ") { return "mailto:\(value)" }
        return nil
    }

    private static func policyID(mode: Mode, mxHosts: [String]) -> String {
        // FNV-1a has a tiny, dependency-free implementation and emits only RFC 8461's permitted
        // alphanumeric ID characters. This is an opaque version marker, not a security primitive.
        let input = ([mode.rawValue] + mxHosts).joined(separator: "\n")
        var hash: UInt64 = 14_695_981_039_346_656_037
        for byte in input.utf8 {
            hash ^= UInt64(byte)
            hash &*= 1_099_511_628_211
        }
        return "a\(String(hash, radix: 36))"
    }
}
