import Foundation
import Observation

@MainActor
@Observable
public final class NewSiteWizardModel {
    public enum Step: Int, CaseIterable { case details, type, look, content, save, building }

    public var step: Step = .details
    public var draft = NewSiteDraft(siteType: .business, name: "")
    /// Drives the Image Playground sheet presentation in the Content step (#92).
    public var showingImagePlayground = false
    public private(set) var progress: [SiteScaffolder.ScaffoldStep] = []
    public private(set) var fatal: SiteScaffolder.ScaffoldStep?   // .failed, if any
    public private(set) var completedSiteID: String?

    public let catalog: ThemeCatalog
    public let defaultSaveDirectory: URL?
    private let slugTaken: @Sendable (String) -> Bool

    public init(catalog: ThemeCatalog, defaultSaveDirectory: URL? = nil, slugTaken: @escaping @Sendable (String) -> Bool) {
        self.catalog = catalog
        self.defaultSaveDirectory = defaultSaveDirectory
        self.slugTaken = slugTaken
        // Seed a default theme for the initial type.
        draft.themeID = catalog.defaultThemeID(for: draft.siteType)
    }

    public var slugPreview: String { SiteSlug.derive(from: draft.name) }

    public var defaultSaveFileName: String { "\(slugPreview).anglesite" }

    /// Non-fatal build warnings (e.g. a failed install), surfaced so a failure isn't hidden behind a dead-end preview (#229).
    public var warnings: [String] {
        progress.compactMap { if case .warning(_, let message) = $0 { return message } else { return nil } }
    }

    public var hasWarnings: Bool { !warnings.isEmpty }

    /// Site registered with no warnings — only then may the wizard open it immediately (else it stays put so warnings are read) (#229).
    public var didCompleteCleanly: Bool { completedSiteID != nil && !hasWarnings }

    public var detailsError: String? {
        let name = draft.name.trimmingCharacters(in: .whitespacesAndNewlines)
        if name.isEmpty { return nil }              // empty is "incomplete", not an error to show
        if slugTaken(slugPreview) { return "A site named \u{201C}\(slugPreview)\u{201D} already exists." }
        return nil
    }

    public var cloudflareDevPreview: String {
        "\(slugPreview).workers.dev"
    }

    public var canContinue: Bool {
        switch step {
        case .details:
            return !draft.name.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
                && detailsError == nil
                && (draft.domainChoice != .transfer || Self.isValidDomain(draft.domain))
        case .type:    return true
        case .look:    return draft.themeID == CustomTheme.id || catalog.theme(id: draft.themeID) != nil
        case .content: return true                  // content is optional
        case .save:    return true
        case .building: return false
        }
    }

    public func choose(type: SiteType) {
        draft.siteType = type
        if draft.themeID != CustomTheme.id {
            draft.themeID = catalog.defaultThemeID(for: type)
        }
    }

    public static func isValidDomain(_ domain: String) -> Bool {
        let trimmed = domain.trimmingCharacters(in: .whitespacesAndNewlines)
        guard trimmed.contains("."),
              trimmed.rangeOfCharacter(from: .whitespacesAndNewlines) == nil,
              trimmed.range(of: #"^[A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?(?:\.[A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?)+$"#,
                            options: .regularExpression) != nil
        else { return false }
        return true
    }

    /// Image Playground generation concepts for the current draft (#92).
    public var heroImageConcepts: [String] {
        HeroImage.concepts(name: draft.name, siteType: draft.siteType, tagline: draft.tagline, imageDescription: draft.heroImagePrompt)
    }

    /// Whether a hero image has been generated and staged for scaffolding.
    public var hasHeroImage: Bool { draft.heroImageURL != nil }

    /// Store the URL of an image generated by Image Playground (or clear it).
    public func setHeroImage(_ url: URL?) { draft.heroImageURL = url }

    public func advance() { if let next = Step(rawValue: step.rawValue + 1) { step = next } }
    public func back() { if let prev = Step(rawValue: step.rawValue - 1) { step = prev } }

    /// Runs the scaffolder, accumulating progress. Returns the new site id on success.
    public func build(using scaffolder: SiteScaffolder) async -> String? {
        step = .building
        if draft.saveFileName.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            draft.saveFileName = defaultSaveFileName
        }
        if draft.headline.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            draft.headline = draft.name
        }
        for await s in scaffolder.scaffold(draft) {
            progress.append(s)
            if case .failed = s { fatal = s }
            if case .done(let id) = s { completedSiteID = id }
        }
        return completedSiteID
    }
}
