import Foundation

/// The kind of site the owner is creating. The wizard collects only these five broad
/// categories; the plugin's fine-grained `bestFor` business types stay with the chat path.
public enum SiteType: String, Sendable, CaseIterable, Codable {
    case business, personal, blog, portfolio, organization, blank

    /// Owner-facing label for the Type step.
    public var label: String {
        switch self {
        case .business:     return "Business website"
        case .personal:     return "Personal website"
        case .blog:         return "Blog"
        case .portfolio:    return "Portfolio"
        case .organization: return "Organization website"
        case .blank:        return "Blank website"
        }
    }

    /// One-sentence explanation for the Type step.
    public var description: String {
        switch self {
        case .business:     return "Promote a company, service, or local shop."
        case .personal:     return "Create a home for your bio, links, and projects."
        case .blog:         return "Publish posts, articles, or updates over time."
        case .portfolio:    return "Showcase selected work, case studies, or creative projects."
        case .organization: return "Share a group mission, programs, events, and ways to get involved."
        case .blank:        return "Start with a simple empty website you can shape yourself."
        }
    }

    /// SF Symbol for the Type step row.
    public var symbol: String {
        switch self {
        case .business:     return "building.2"
        case .personal:     return "person.crop.circle"
        case .blog:         return "text.alignleft"
        case .portfolio:    return "square.grid.2x2"
        case .organization: return "person.3"
        case .blank:        return "doc"
        }
    }
}

/// How the owner wants to handle the public domain for the website.
public enum NewSiteDomainChoice: String, Sendable, CaseIterable, Codable {
    case buy
    case transfer
    case later
}

/// Reserved theme identifier used when the owner chooses their own colors in the wizard.
public enum CustomTheme {
    public static let id = "__custom"
    public static let defaultPrimary = "#2563eb"
    public static let defaultAccent = "#f59e0b"

    public static func make(primary: String, accent: String) -> Theme {
        Theme(
            id: id,
            name: "Custom",
            blurb: "Your own colors",
            swatch: [primary, accent],
            cssVars: [
                "color-primary": primary,
                "color-accent": accent,
                "font-heading": "system-ui, -apple-system, sans-serif",
                "font-body": "system-ui, -apple-system, sans-serif",
            ]
        )
    }
}

/// Everything the wizard collects before scaffolding. A plain value — no behavior.
public struct NewSiteDraft: Sendable, Equatable {
    public var siteType: SiteType
    public var name: String
    public var domainChoice: NewSiteDomainChoice
    public var domain: String
    public var tagline: String
    public var saveDirectory: URL?
    public var saveFileName: String
    public var themeID: String
    public var customPrimaryColor: String
    public var customAccentColor: String
    public var logoURL: URL?
    public var headline: String
    public var blurb: String
    public var heroImagePrompt: String
    /// File URL of an optional hero image generated by Image Playground (#92). When set, the
    /// scaffolder copies it into the site's asset dir and references it from the homepage. Nil
    /// when the owner skipped generation or Apple Intelligence is unavailable.
    public var heroImageURL: URL?

    public init(
        siteType: SiteType,
        name: String,
        domainChoice: NewSiteDomainChoice = .later,
        domain: String = "",
        tagline: String = "",
        saveDirectory: URL? = nil,
        saveFileName: String = "",
        themeID: String = "",
        customPrimaryColor: String = CustomTheme.defaultPrimary,
        customAccentColor: String = CustomTheme.defaultAccent,
        logoURL: URL? = nil,
        headline: String? = nil,
        blurb: String = "",
        heroImagePrompt: String = "",
        heroImageURL: URL? = nil
    ) {
        self.siteType = siteType
        self.name = name
        self.domainChoice = domainChoice
        self.domain = domain
        self.tagline = tagline
        self.saveDirectory = saveDirectory
        self.saveFileName = saveFileName
        self.themeID = themeID
        self.customPrimaryColor = customPrimaryColor
        self.customAccentColor = customAccentColor
        self.logoURL = logoURL
        // Default the homepage headline to the site name so step 4 starts pre-filled.
        self.headline = headline ?? name
        self.blurb = blurb
        self.heroImagePrompt = heroImagePrompt
        self.heroImageURL = heroImageURL
    }
}

/// Derives a filesystem-safe folder slug from a site name.
public enum SiteSlug {
    /// Lowercases, transliterates non-Latin characters to Latin, strips diacritics,
    /// and collapses any run of non-alphanumeric characters to a single hyphen.
    public static func derive(from name: String) -> String {
        let transliterated = name.applyingTransform(.toLatin, reverse: false) ?? name
        let folded = transliterated.folding(options: .diacriticInsensitive, locale: Locale(identifier: "en_US_POSIX"))
        var out = ""
        var lastWasHyphen = false
        for scalar in folded.lowercased().unicodeScalars {
            if (scalar >= "a" && scalar <= "z") || (scalar >= "0" && scalar <= "9") {
                out.unicodeScalars.append(scalar)
                lastWasHyphen = false
            } else if !lastWasHyphen {
                out.append("-")
                lastWasHyphen = true
            }
        }
        let trimmed = out.trimmingCharacters(in: CharacterSet(charactersIn: "-"))
        return trimmed.isEmpty ? "untitled-site" : trimmed
    }
}
